var WIDTH = window.innerWidth;
var HEIGHT = window.innerHeight;
var spaceScale = 1000.0;
var scaleMultiplier = 10.0 ;
var flyingDuration = 500;
var FLY_STOP_DISTANCE = 2.0;
var spriteJSONPath = './pic/Super Mario World (USA)_3D.json';
var adjacentMoments = 20;
var autoRotateSpeed = 0.05;
var manager = new THREE.LoadingManager();
var fileLoader = new THREE.FileLoader(manager);
var textureLoader = new THREE.TextureLoader(manager);
var imageLoader = new THREE.ImageLoader(manager);
var raycaster = new THREE.Raycaster();
var mouse = new THREE.Vector2();

// var floating_div = document.getElementById('float_div');
// var FLOATING_DIV_RIGHT = floating_div.offsetLeft + floating_div.clientWidth;
// var FLOATING_DIV_BOTTOM = floating_div.offsetTop + floating_div.clientHeight;
